In [13]:
import pandas as pd
data = {
    "student_ID": [101,102,103,104,105,106,107,108],
    "student": ["Asha","Ravi","priya","john","anu","kiran","ravi","meena"],
    "department": ["cse","cse","ece","ece","cse","eee","cse","eee"],
    "attendence": [90,75,95,60,80,70,75,85],
    "internalmarks": [85,70,90,55,78,65,70, None],
    "final_marks": [88,72,92,50,80,68,72,82]
    }

In [15]:
df=pd.DataFrame(data)
df.to_csv("student.csv",index=False)
print("student.csv created succesfully")

student.csv created succesfully

In [16]:
df = pd.read_csv("student.csv")
print("origonal dataset")
print(df)

origonal dataset
   student_ID student department  attendence  internalmarks  final_marks
0         101    Asha        cse          90           85.0           88
1         102    Ravi        cse          75           70.0           72
2         103   priya        ece          95           90.0           92
3         104    john        ece          60           55.0           50
4         105     anu        cse          80           78.0           80
5         106   kiran        eee          70           65.0           68
6         107    ravi        cse          75           70.0           72
7         108   meena        eee          85            NaN           82

In [17]:
print("\nfirst five record:")
print(df.head())

first five record:
   student_ID student department  attendence  internalmarks  final_marks
0         101    Asha        cse          90           85.0           88
1         102    Ravi        cse          75           70.0           72
2         103   priya        ece          95           90.0           92
3         104    john        ece          60           55.0           50
4         105     anu        cse          80           78.0           80

In [18]:
print("\nlast five record:")
print(df.tail())

last five record:
   student_ID student department  attendence  internalmarks  final_marks
3         104    john        ece          60           55.0           50
4         105     anu        cse          80           78.0           80
5         106   kiran        eee          70           65.0           68
6         107    ravi        cse          75           70.0           72
7         108   meena        eee          85            NaN           82

In [19]:
print(df.shape)

(8, 6)

In [21]:
df.dtypes

student_ID         int64
student           object
department        object
attendence         int64
internalmarks    float64
final_marks        int64
dtype: object

In [22]:
df.describe()

       student_ID  attendence  internalmarks  final_marks
count     8.00000    8.000000       7.000000     8.000000
mean    104.50000   78.750000      73.285714    75.500000
std       2.44949   11.259916      11.996031    13.212548
min     101.00000   60.000000      55.000000    50.000000
25%     102.75000   73.750000      67.500000    71.000000
50%     104.50000   77.500000      70.000000    76.000000
75%     106.25000   86.250000      81.500000    83.500000
max     108.00000   95.000000      90.000000    92.000000

In [23]:
df.describe()

       student_ID  attendence  internalmarks  final_marks
count     8.00000    8.000000       7.000000     8.000000
mean    104.50000   78.750000      73.285714    75.500000
std       2.44949   11.259916      11.996031    13.212548
min     101.00000   60.000000      55.000000    50.000000
25%     102.75000   73.750000      67.500000    71.000000
50%     104.50000   77.500000      70.000000    76.000000
75%     106.25000   86.250000      81.500000    83.500000
max     108.00000   95.000000      90.000000    92.000000

In [24]:
print(df.isnull().sum())

student_ID       0
student          0
department       0
attendence       0
internalmarks    1
final_marks      0
dtype: int64

In [26]:
print(df.duplicated().sum())
df =df.drop_duplicates()

0

In [27]:
print("average final marks by department")
print(
    df.groupby("department")["final_marks"].mean()
)

average final marks by department
department
cse    78.0
ece    71.0
eee    75.0
Name: final_marks, dtype: float64

In [30]:
courses = pd.DataFrame({
    "student_ID": [101,102,103,104,105,106,107,108],
    "Courses" : [
        "py","hindi","math","kannad","bio","py","math","hindi2"
    ]
})

In [31]:
merge_df = df.merge(courses,on="student_ID")
print(merge_df)

   student_ID student department  attendence  internalmarks  final_marks  \
0         101    Asha        cse          90           85.0           88
1         102    Ravi        cse          75           70.0           72
2         103   priya        ece          95           90.0           92
3         104    john        ece          60           55.0           50
4         105     anu        cse          80           78.0           80
5         106   kiran        eee          70           65.0           68
6         107    ravi        cse          75           70.0           72
7         108   meena        eee          85            NaN           82

  Courses
0      py
1   hindi
2    math
3  kannad
4     bio
5      py
6    math
7  hindi2